### ISSUE TITLE
Wrong count of bombs if width is 1

### ISSUE THREAD

**Issue by danon** [cerbin1/MinesweeperJS#2]
I've set up 8 bombs on board 1x9, and as you can see this cell is surrounded by 2 bombs, but couter says it's 3.

![image](https://cloud.githubusercontent.com/assets/13367735/21626439/5cc6c744-d211-11e6-9253-e4cd905c16b2.png)

**Comment by cerbin1** [comment]
I have tried like 50x times to find that bug, but it seems like it does not longer occurs

**Comment by danon** [comment]
Maybe because now we're regenerating board after clicking on first click on bomb.
